#!/usr/bin/env python

"""Wrapper script on desitarget.mock.targets_truth which should be called by
sprint-healpix-slurm.

"""
from __future__ import print_function, division

import yaml
import argparse

from desispec.log import get_logger
from desitarget.mock.build import targets_truth

parser = argparse.ArgumentParser()
parser.add_argument('--config', '-c',default='input.yaml')
parser.add_argument('--output_dir', help='Output directory.', type=str, default='./')
parser.add_argument('--seed', '-s', help='Seed for random number generation', type=int, default=None)
parser.add_argument('--bounds', help='minra, maxra, mindec, maxdec', type=float64,
                    nargs=4, default=(0.0, 360.0, -90.0, 90.0))
parser.add_argument('--nproc', type=int, help='number of concurrent processes to use', default=24)
args = parser.parse_args()

log = get_logger()

log.info('Reading configuration file {}'.format(args.config))
with open(args.config, 'r') as pfile:
    params = yaml.load(pfile)

ramin, ramax, decmin, decmax = args.bounds
params['subset']['min_ra'] = ramin
params['subset']['max_ra'] = ramax
params['subset']['min_dec'] = decmin
params['subset']['max_dec'] = decmax

targets_truth(params, args.output_dir, seed=args.seed, nside=64, 
              nproc=args.nproc, verbose=True, clobber=True)
